In [1]:
import pandas as pd
import numpy as np

print(pd.__version__)

3.0.3

In [2]:
df = pd.read_excel(r"C:\Users\jaysr\OneDrive\Desktop\FutureSkillsAI\indian-job-market-dataset-2025.xlsx")

In [3]:
df.head()

,title,jobId,currency,jobUploaded,companyName,tagsAndSkills,experience,salary,location,companyId,ReviewsCount,AggregateRating,jobDescription,minimumSalary,maximumSalary,minimumExperience,maximumExperience
0,Sr. HR Recruiter (NON IT),270925008041,INR,6 Days Ago,Orion,"Communication,Manpower,Staffing,Convincing Pow...",2-4 Yrs,2-4 Lacs PA,Kolkata(Chinar Park),645563,NaN,NaN,Preferred candidate profile . .,200000.0,400000.0,2.0,4.0
1,Fire And Safety Officer,270925007584,INR,6 Days Ago,"Apollo Hospitals International Limited, Ahmedabad","Safety Officer Activities,Fire Protection,Fire...",6-11 Yrs,3-5 Lacs PA,"Gandhinagar, Ahmedabad",14072,5162.0,4.0,"Ensure active Fire Protection System,such as F...",300000.0,500000.0,6.0,11.0
2,Opening For Performance Marketing - Chennai,270925007492,INR,6 Days Ago,TVS Credit Services Ltd,"Performance Marketing,User Acquisition,growth ...",12-18 Yrs,Not disclosed,Chennai,1324750,2892.0,4.2,MBA Marketing (preferred Tier II or III B- Sch...,0.0,0.0,12.0,18.0
3,Medical Billing Executive,270925007443,INR,6 Days Ago,GNR Global Services,"Fluent English,Spoken English,Good English Com...",0-3 Yrs,"70,000-2 Lacs PA","Mohali, Chandigarh, Kharar, Zirakpur",123804403,NaN,NaN,Job Title-Medical Billing Executive\nLocation-...,70000.0,200000.0,0.0,3.0
4,Senior Group Product Manager - CNS Therapy,270925007430,INR,6 Days Ago,Cadila Pharmaceuticals,"Product Marketing,CNS,Product Management,Nephr...",5-10 Yrs,8-18 Lacs PA,Ahmedabad,14957,2134.0,3.4,Principal Tasks & Responsibilities : (Please w...,800000.0,1800000.0,5.0,10.0

In [4]:
df.shape

(97929, 17)

In [5]:
df.columns.tolist()

['title',
 'jobId',
 'currency',
 'jobUploaded',
 'companyName',
 'tagsAndSkills',
 'experience',
 'salary',
 'location',
 'companyId',
 'ReviewsCount',
 'AggregateRating',
 'jobDescription',
 'minimumSalary',
 'maximumSalary',
 'minimumExperience',
 'maximumExperience']

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 97929 entries, 0 to 97928
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   title              97929 non-null  str
 1   jobId              97929 non-null  int64
 2   currency           97929 non-null  str
 3   jobUploaded        97929 non-null  str
 4   companyName        97925 non-null  str
 5   tagsAndSkills      97358 non-null  str
 6   experience         95824 non-null  str
 7   salary             97929 non-null  str
 8   location           97929 non-null  str
 9   companyId          97929 non-null  int64
 10  ReviewsCount       62677 non-null  float64
 11  AggregateRating    62677 non-null  float64
 12  jobDescription     97929 non-null  str
 13  minimumSalary      97358 non-null  float64
 14  maximumSalary      97358 non-null  float64
 15  minimumExperience  97358 non-null  float64
 16  maximumExperience  97358 non-null  float64
dtypes: float64(6), int64(2), str(9)
memory usage: 12.7 MB

In [7]:
df.isnull().sum()

title                    0
jobId                    0
currency                 0
jobUploaded              0
companyName              4
tagsAndSkills          571
experience            2105
salary                   0
location                 0
companyId                0
ReviewsCount         35252
AggregateRating      35252
jobDescription           0
minimumSalary          571
maximumSalary          571
minimumExperience      571
maximumExperience      571
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(247)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
columns = [
    "title",
    "companyName",
    "location",
    "experience",
    "salary",
    "jobDescription",
    "tagsAndSkills",
    "jobUploaded",
    "minimumSalary",
    "maximumSalary",
    "minimumExperience",
    "maximumExperience"
]

df = df[columns]

In [12]:
df["title"] = df["title"].str.strip()

In [13]:
tech_keywords = [
    "Software Engineer",
    "Software Developer",
    "Java Developer",
    "Python Developer",
    "Data Analyst",
    "Data Scientist",
    "Data Engineer",
    "Business Analyst",
    "Machine Learning Engineer",
    "AI Engineer",
    "DevOps Engineer",
    "Cloud Engineer",
    "QA Engineer",
    "Automation Test Engineer",
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Web Developer",
    "SAP Consultant",
    "BI Developer"
]

In [15]:
pattern = "|".join(tech_keywords)

In [16]:
tech_df = df[
    df["title"].str.contains(pattern, case=False, na=False)
]

In [17]:
exclude = [
    "Sales",
    "Marketing",
    "Recruiter",
    "HR",
    "Business Development",
    "Customer",
    "Finance",
    "Mechanical",
    "Civil",
    "Medical",
    "BPO",
    "Voice",
    "Non Voice",
    "Telecaller"
]

In [18]:
exclude_pattern = "|".join(exclude)

In [19]:
tech_df = tech_df[
    ~tech_df["title"].str.contains(
        exclude_pattern,
        case=False,
        na=False
    )
]

In [20]:
tech_df.shape

(6877, 12)

In [21]:
tech_df["title"].value_counts().head(20)

title
Data Engineer                338
Java Full Stack Developer    282
Java Developer               253
Senior Software Engineer     207
Business Analyst             172
Software Engineer            164
Senior Data Engineer         116
Data Scientist               108
Devops Engineer               80
Data Analyst                  79
Python Developer              74
Full Stack Developer          64
Big Data Engineer             61
Senior Data Scientist         55
Senior Java Developer         49
DevOps Engineer               49
Software Developer            47
Sr. Software Engineer         45
Lead Software Engineer        42
Python Software Developer     40
Name: count, dtype: int64

In [22]:
salary_df = tech_df[
    (tech_df["minimumSalary"] > 0) &
    (tech_df["maximumSalary"] > 0)
]

In [23]:
salary_df = salary_df.copy()

salary_df["averageSalary"] = (
    salary_df["minimumSalary"] +
    salary_df["maximumSalary"]
) / 2

In [24]:
skills = (
    tech_df["tagsAndSkills"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)

In [25]:
skills = skills.replace({
    "python":"Python",
    "sql":"SQL",
    "javascript":"JavaScript",
    "css":"CSS",
    "html":"HTML",
    "aws":"AWS",
    "react.js":"React",
    "spring boot":"Spring Boot",
    "hibernate":"Hibernate",
    "gcp":"GCP",
    "oracle":"Oracle",
    "agile":"Agile"
})

In [26]:
remove_skills = [
    "Application development",
    "Software development",
    "Development methodologies",
    "Computer science",
    "Project Management",
    "Backend",
    "Debugging"
]

skills = skills[
    ~skills.isin(remove_skills)
]

In [47]:
top_skills = skills.value_counts()

In [28]:
top_skills.head(20)

tagsAndSkills
Python                    1729
SQL                       1123
Java                       982
Spring Boot                790
Development                655
AWS                        654
Microservices              583
CSS                        513
Agile                      467
Javascript                 428
java                       419
continuous integration     419
Automation                 390
Hibernate                  386
GCP                        374
Data                       366
HTML                       326
Angular                    309
React.Js                   303
Spring                     292
Name: count, dtype: int64

In [33]:
tech_df[tech_df["title"].str.contains("Sales", case=False, na=False)]

Empty DataFrame
Columns: [title, companyName, location, experience, salary, jobDescription, tagsAndSkills, jobUploaded, minimumSalary, maximumSalary, minimumExperience, maximumExperience]
Index: []

In [34]:
len(tech_df)

6877

In [35]:
tech_df["companyName"].value_counts().head(10)

companyName
Purview India Consulting And  Services  Llp    279
Infosys                                        233
Accenture                                      179
IDESLABS PRIVATE LIMITED                       157
Talent21                                       118
Incedo                                         109
IBM                                             96
Wenger & Watson                                 92
PRADEEPIT CONSULTING SERVICES PVT LTD           91
Purview Services                                84
Name: count, dtype: int64

In [36]:
tech_df["location"].value_counts().head(10)

location
Bengaluru             1471
Hyderabad              686
Pune                   578
Chennai                386
Gurugram               237
Remote                 232
Hybrid - Bengaluru     217
Mumbai                 208
Noida                  167
Hybrid - Pune          130
Name: count, dtype: int64

In [37]:
tech_df["experience"].value_counts()

experience
5-10 Yrs     799
3-8 Yrs      425
6-11 Yrs     413
5-8 Yrs      357
4-9 Yrs      314
            ...
1-13 Yrs       1
3-14 Yrs       1
3-17 Yrs       1
11-12 Yrs      1
1-8 Yrs        1
Name: count, Length: 138, dtype: int64

In [39]:
pd.set_option("display.float_format", "{:,.2f}".format)

In [40]:
salary_df["averageSalary"].describe()

count       1,424.00
mean    1,576,589.04
std       836,936.84
min           786.00
25%     1,000,000.00
50%     1,500,000.00
75%     2,000,000.00
max     8,000,000.00
Name: averageSalary, dtype: float64

In [41]:
salary_df.groupby("title")["averageSalary"] \
.mean() \
.sort_values(ascending=False) \
.head(10)

title
Principal Software Engineer - ROR                       8,000,000.00
Manager, Data Engineering                               6,000,000.00
JP Morgan - Lead Data Scientist                         5,500,000.00
Head - Data Engineering - AL/ML                         5,000,000.00
Lead Data engineer- US MNC (analytics)                  4,750,000.00
Staff Software Developer                                4,500,000.00
Technical Lead, Data Engineering                        4,500,000.00
Senior Python Backend Developers                        4,250,000.00
Lead AI Engineer - Custom Solutions - Bengaluru         4,250,000.00
Sr. Java Developer - IT - Global - Ernakulam - Kerala   4,000,000.00
Name: averageSalary, dtype: float64

In [42]:
salary_df.groupby("companyName")["averageSalary"] \
.mean() \
.sort_values(ascending=False) \
.head(10)

companyName
Mijas Consultants                    8,000,000.00
Neuenco (neuron Encoding Projects)   6,000,000.00
PEI                                  5,750,000.00
InterviewPanel                       5,500,000.00
Binarystar Searchx                   5,000,000.00
Assent Inc                           4,666,666.67
Vichara Technologies                 4,625,000.00
ACV Auctions                         4,500,000.00
Gitcs India                          4,250,000.00
Workoid Consultants                  4,250,000.00
Name: averageSalary, dtype: float64

In [43]:
salary_df.groupby("location")["averageSalary"] \
.mean() \
.sort_values(ascending=False) \
.head(10)

location
Bengaluru(Varthur)                                                                   5,500,000.00
Hybrid - Kolkata, Hyderabad, Delhi / NCR                                             4,625,000.00
Hybrid - Chennai(OMR)                                                                4,500,000.00
Bengaluru(Lavelle Road)                                                              4,250,000.00
Ernakulam                                                                            4,000,000.00
Hybrid - Bengaluru(Bellandur)                                                        3,750,000.00
Bengaluru(M.G Road)                                                                  3,625,000.00
Kochi(Infopark)                                                                      3,500,000.00
Hybrid - Hyderabad, Chennai, Coimbatore                                              3,500,000.00
Hybrid - Hyderabad(Gachibowli), Pune(Kharadi), Bengaluru(Electronics City Phase 1)   3,250,000.00
Name: averageSalary, dtype: float64

In [44]:
tech_df.to_csv(
    r"C:\Users\jaysr\OneDrive\Desktop\FutureSkillsAI\Data\clean_tech_jobs.csv",
    index=False
)

In [45]:
salary_df.to_csv(
    r"C:\Users\jaysr\OneDrive\Desktop\FutureSkillsAI\Data\salary_data.csv",
    index=False
)

In [46]:
top_skills.to_csv(
    r"C:\Users\jaysr\OneDrive\Desktop\FutureSkillsAI\Data\top_skills.csv"
)